package com.siglo21.swiftlogix.application.controller.soporte;

import lombok.Getter;
import lombok.Setter;
import org.springframework.web.bind.annotation.GetMapping;

@Setter
@Getter
public class responseKeycloak {

    /*
    * {
    "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJtdEdKeGRhYXk0YXFIR09wSW40dTZQLXdDbmY5cGJ4QmpJWjh4NnBCay1VIn0.eyJleHAiOjE3MDQ0NjkxNzEsImlhdCI6MTcwNDQ2NzM3MSwianRpIjoiM2RkZmY1ZjEtZjdiYi00YmU4LTk2ZjQtYjcxZjc3NmI1YjIwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL2F1dGgvcmVhbG1zL3NpZ2xvMjEiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiMDI3ZDI2Y2QtNDcwMC00ZmYwLWFmYWEtNDI3ODQzYzMyMGJmIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic2lnbG8yMS1jbGllbnQtYXBpLXJlc3QiLCJzZXNzaW9uX3N0YXRlIjoiZTdjYzY5MTUtZDBjNC00NTcxLWE3OTEtNWNiNmJiNjUzYzVhIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXNpZ2xvMjEiLCJ2ZW5kZWRvciIsImFkbWluaXN0cmFkb3IiLCJyZXBhcnRpZG9yIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InNpZ2xvMjEtY2xpZW50LWFwaS1yZXN0Ijp7InJvbGVzIjpbInJlcGFydGlkb3ItY2xpZW50ZS1yb2wiLCJ2ZW5kZWRvci1jbGllbnRlLXJvbCIsImFkbWluaXN0cmFkb3ItY2xpZW50ZS1yb2wiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6ImU3Y2M2OTE1LWQwYzQtNDU3MS1hNzkxLTVjYjZiYjY1M2M1YSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWxlam8uZGV2In0.VYSwdf-Dorv3PwEpRqeB0HDv22XHl2gxU0893HqUrgTkagwqItb2OkVv3UhQUYjhQrb1rY6whxX11VQTd-9sPxHs7mrQJpPBZL1gT_V9xIp-t_1devt_zhSmJuZjtSxCDuHhhiyaOZEEH856NdApO6qPLT2BC-7hpgvpjlhBUzpREG_NuUp2_s5epilJTVEGuemUhuLBD1aB1Fqmx6b5SVQH7MrNUb6y6I7P_-YSsGX_fdQ0dHr8wpCdCkfT-XfX2yvtV_BYeh7rGsCfLOnaZhWRqYzu4uvc4d7deOTlGEECYSc6Xmols7NvqbAgbYBYnXjCSS7HPtrwFdSJSnvIWw",
    "expires_in": 1800,
    "refresh_expires_in": 1800,
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhMjhjMWM1MC1iMDJlLTQwYTktOWNjMy04YzkzM2U4NDA4YmQifQ.eyJleHAiOjE3MDQ0NjkxNzEsImlhdCI6MTcwNDQ2NzM3MSwianRpIjoiYTBmYjk2ZTctNTQzMi00NDBjLWFmZTAtYTUyNjVkYTJhMDY2IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL2F1dGgvcmVhbG1zL3NpZ2xvMjEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgxODAvYXV0aC9yZWFsbXMvc2lnbG8yMSIsInN1YiI6IjAyN2QyNmNkLTQ3MDAtNGZmMC1hZmFhLTQyNzg0M2MzMjBiZiIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJzaWdsbzIxLWNsaWVudC1hcGktcmVzdCIsInNlc3Npb25fc3RhdGUiOiJlN2NjNjkxNS1kMGM0LTQ1NzEtYTc5MS01Y2I2YmI2NTNjNWEiLCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzaWQiOiJlN2NjNjkxNS1kMGM0LTQ1NzEtYTc5MS01Y2I2YmI2NTNjNWEifQ.NdCviKGgfreeuaNOIzyChTIdhC02bmVusscBGxwCGdA",
    "token_type": "Bearer",
    "not-before-policy": 0,
    "session_state": "e7cc6915-d0c4-4571-a791-5cb6bb653c5a",
    "scope": "email profile"
}
    * */

    private String access_token;
    private String expires_in;
    private String refresh_expires_in;
    private String refresh_token;
    private String token_type;
    private String not_before_policy;
    private String session_state;
    private String scope;


}
