# Establecer la imagen base de Node.js
FROM node:16-alpine as build

# Crear el directorio de trabajo en la imagen
WORKDIR /app

# Copiar package.json (y package-lock.json si está presente)
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código fuente del proyecto
COPY . .

RUN npm run build

# Construir la aplicación para producción
#RUN npm run build

# Etapa de producción
#FROM node:16-alpine

#WORKDIR /app

#COPY --from=build /app/next.config.js ./
#COPY --from=build /app/public ./public
#COPY --from=build /app/.next ./.next
#COPY --from=build /app/node_modules ./node_modules

# El puerto en el que se ejecutará la aplicación
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["npm", "run", "start"]
