# Establecer la imagen base de Node.js
FROM node:16-alpine as build

# Crear el directorio de trabajo en la imagen
WORKDIR /app

# Copiar package.json (y package-lock.json si está presente)
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código fuente del proyecto
COPY . .
# Copiar el archivo .env.docker a .env
COPY .env.docker .env

# Construir la aplicación
RUN npm run build

# El puerto en el que se ejecutará la aplicación
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["npm", "run", "start"]
