version: '3.9'

services:
  swiftlogix:
    container_name: swiftlogix
    build: swiftlogix
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql

  mysql:
    container_name: mysqlContainer
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=andes2020
      - MYSQL_DATABASE=swiftlogix
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=andes2020
    volumes:
      - ./db/mysql_data:/var/lib/mysql

  keycloak:
    container_name: keycloakContainer
    image: jboss/keycloak
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_USER=administrador
      - KEYCLOAK_PASSWORD=andes2020
      - DB_VENDOR=mysql
      - DB_ADDR=mysql
      - DB_DATABASE=swiftlogix
      - DB_USER=dev
      - DB_PASSWORD=andes2020
    depends_on:
      - mysql

