version: '3.9'

networks:
  mynetwork:
    driver: bridge

services:
  swiftlogix:
    container_name: swiftlogix
    build: swiftlogix
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    container_name: mysqlContainer
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=andes2020
      - MYSQL_DATABASE=swiftlogix
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=andes2020
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  frontend:
    container_name: react_frontend
    build: frontEnd
    ports:
      - "3000:3000"
    depends_on:
      - swiftlogix
    networks:
      - mynetwork

  keycloak:
    container_name: keycloakContainer
    image: jboss/keycloak
    ports:
      - "8180:8080"
    volumes:
      - ./mi-tema/keywind/theme/keywind/.:/opt/jboss/keycloak/themes/keywind
    environment:
      - KEYCLOAK_USER=administrador
      - KEYCLOAK_PASSWORD=andes2020
      - KEYCLOAK_DEVEL=true
      - DB_VENDOR=mysql
      - DB_ADDR=mysql
      - DB_DATABASE=swiftlogix
      - DB_USER=dev
      - DB_PASSWORD=andes2020
    depends_on:
      - mysql
    networks:
      - mynetwork
