version: '3.9'

services:
  swiftlogix:
    container_name: swiftlogix
    build: ./SwiftLogix
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql

  frontend:
    container_name: react_frontend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - swiftlogix


